testStrings = "testStrings"
testDoubles = 10.1
testIntegerList = [2, 3]
testIntegers = 64
testBooleans = true
testStringList = ["testItem1", "testItem2"]
testObjects = "testObjects"
testLongs = 100

[testStringToObjectMap]
key1 = "value2"
key2 = "value2"

[testClass]
value = 1.0
